version: '3'
services:
  frp_server:
    image: geektr/frp
    restart: always
    env_file:
      - "./.env"
    volumes:
      - "./frps.ini:/etc/frp/frps.ini:ro"
    port:
      - "${BIND_TCP_PORT}"
      - "${BIND_UDP_PORT}"
      - "${DASHBOARD_PORT}"
      - "${PORT_RANGE}"
